#!/usr/bin/env bash
#
# Mike Word Add-in — one-command local dev setup + launch.
#
#   bash apps/word-addin/scripts/dev.sh
#
# What it does (idempotent — safe to re-run):
#   1. Verifies Node + (optionally) the Supabase CLI are available.
#   2. Reads the local Supabase URL + anon key from `supabase status` and writes
#      apps/word-addin/.env.development (the webpack build reads these at compile
#      time, so they must be present before the bundle is built).
#   3. Runs `npm install` if node_modules is missing.
#   4. Checks the Mike API is reachable (warns, does not fail, if not).
#   5. Installs the trusted dev HTTPS certificate if Word doesn't already trust it
#      (this step may prompt for your keychain/admin password).
#   6. Sources the env and runs `npm start`, which boots the webpack dev server on
#      https://localhost:3000 and sideloads the add-in into Word desktop.
#
# Pass --setup-only to do everything except the final `npm start` (steps 1-5).
#
set -euo pipefail

SETUP_ONLY=0
[ "${1:-}" = "--setup-only" ] && SETUP_ONLY=1

cd "$(dirname "$0")/.."          # -> apps/word-addin
ADDIN_DIR="$(pwd)"
ROOT_DIR="$(cd ../.. && pwd)"    # -> repo root

step() { printf "\n\033[1;34m==> %s\033[0m\n" "$1"; }
ok()   { printf "    \033[1;32m✔\033[0m %s\n" "$1"; }
warn() { printf "    \033[1;33m! %s\033[0m\n" "$1"; }

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
step "Checking prerequisites"
command -v node >/dev/null 2>&1 || { echo "Node.js 18+ is required (https://nodejs.org)"; exit 1; }
ok "node $(node --version)"
HAVE_SUPABASE=1
command -v supabase >/dev/null 2>&1 || { HAVE_SUPABASE=0; warn "supabase CLI not found — can't auto-read the anon key"; }

# ── 2. Read local Supabase config ────────────────────────────────────────────
step "Reading local Supabase config"
SUPA_URL=""; ANON=""
if [ "$HAVE_SUPABASE" = 1 ]; then
    STATUS_JSON="$(supabase status 2>/dev/null | sed -n '/^{/,/^}/p' || true)"
    get() { printf '%s' "$STATUS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin).get('$1',''))" 2>/dev/null || true; }
    SUPA_URL="$(get API_URL)"
    ANON="$(get ANON_KEY)"
fi
API_BASE="${REACT_APP_API_BASE_URL:-http://localhost:3001}"

# ── 3. Write .env.development ─────────────────────────────────────────────────
# The add-in is served over HTTPS (Word requires it) but the local backends are
# HTTP — Word's WebView blocks that mix. So the bundle points at SAME-ORIGIN
# HTTPS paths on the dev server, which proxies them to the real HTTP backends
# (see the proxy config in webpack.config.js). The real backend URLs are kept in
# SUPA_URL / API_BASE for health checks and the proxy targets.
step "Configuring .env.development (proxied through the HTTPS dev server)"
DEV_ORIGIN="https://localhost:3000"
# Preserve an existing anon key if we couldn't read it from `supabase status`.
if [ -z "$ANON" ] && [ -f .env.development ]; then
    ANON="$(grep '^REACT_APP_SUPABASE_ANON_KEY=' .env.development | cut -d= -f2- || true)"
fi
cat > .env.development <<EOF
# Generated by scripts/dev.sh. URLs point at the dev server's HTTPS proxy
# (webpack.config.js) so the task pane never makes blocked HTTP requests.
REACT_APP_SUPABASE_URL=${DEV_ORIGIN}
REACT_APP_SUPABASE_ANON_KEY=${ANON}
REACT_APP_API_BASE_URL=${DEV_ORIGIN}/api
EOF
if [ -n "$ANON" ]; then
    ok "wrote proxied URLs + anon key"
else
    warn "No anon key yet. Start Supabase (bash scripts/setup-local.sh) and re-run."
fi

# ── 4. Dependencies ──────────────────────────────────────────────────────────
step "Installing dependencies"
if [ -d node_modules ]; then
    ok "node_modules present (run 'npm install' manually to update)"
else
    npm install
    ok "dependencies installed"
fi

# ── 5. Mike backend health (Supabase + API) ──────────────────────────────────
# The add-in is useless without the backend: sign-in goes directly to Supabase
# (/auth/v1/token) and uploads use Supabase storage, while chat/actions/workflows/
# projects all call the Mike API. Verify BOTH are up before launching.
step "Checking the Mike backend is running"
BACKEND_OK=1

# 5a. Local Supabase — required for sign-in and document storage.
SUPA_HEALTH_URL="${SUPA_URL:-http://127.0.0.1:54321}/auth/v1/health"
supa_code="$(curl -s -m5 -o /dev/null -w '%{http_code}' "$SUPA_HEALTH_URL" 2>/dev/null)" || true
[ -n "$supa_code" ] || supa_code=000
if [ "$supa_code" = "200" ]; then
    ok "Supabase reachable (${SUPA_URL:-http://127.0.0.1:54321})"
else
    BACKEND_OK=0
    warn "Supabase NOT reachable (HTTP $supa_code) — sign-in and uploads will fail."
    warn "Start it from the repo root:  bash scripts/setup-local.sh"
fi

# 5b. Mike API plus its db + storage dependencies, via GET /ready.
ready_json="$(curl -s -m6 "$API_BASE/ready" 2>/dev/null || true)"
ready_flags="$(printf '%s' "$ready_json" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin); c = d.get("checks", {})
    print(int(bool(d.get("ok"))),
          int(bool(c.get("db", {}).get("ok"))),
          int(bool(c.get("storage", {}).get("ok"))))
except Exception:
    print(0, 0, 0)
' 2>/dev/null || echo "0 0 0")"
set -- $ready_flags; api_ok="$1"; db_ok="$2"; st_ok="$3"
if [ "$api_ok" = "1" ]; then
    ok "Mike API healthy at $API_BASE (db + storage OK)"
else
    BACKEND_OK=0
    if [ -z "$ready_json" ]; then
        warn "Mike API NOT reachable at $API_BASE."
    else
        warn "Mike API is up but dependencies are unhealthy (db_ok=$db_ok storage_ok=$st_ok)."
    fi
    warn "Start it from the repo root:  npm run dev:api"
fi

# ── 6. Dev HTTPS certificate ─────────────────────────────────────────────────
step "Checking dev HTTPS certificate"
if npx --no-install office-addin-dev-certs verify >/dev/null 2>&1; then
    ok "dev certificate already trusted"
else
    warn "Installing the trusted dev cert (Word rejects untrusted HTTPS)."
    warn "This may prompt for your keychain/admin password…"
    npx office-addin-dev-certs install
    warn "Cert installed — fully QUIT Word (Cmd-Q) before launching so it reloads trust."
fi

# ── 7. Launch ────────────────────────────────────────────────────────────────
if [ "$SETUP_ONLY" = 1 ]; then
    step "Setup complete"
    [ "$BACKEND_OK" = 1 ] || warn "Backend is not fully up — start Mike before launching (see above)."
    echo "    To launch: cd $ADDIN_DIR && set -a && source .env.development && set +a && npm start"
    exit 0
fi

if [ "$BACKEND_OK" != 1 ]; then
    step "Mike backend is not running"
    echo "    The add-in needs Mike running before it does anything useful. Start it:"
    echo "      (repo root, once)  bash scripts/setup-local.sh   # if Supabase is down"
    echo "      (repo root)        npm run dev:api               # the Mike API"
    echo "    Then re-run this script. To launch anyway, set FORCE=1 (sign-in will fail until Mike is up)."
    [ "${FORCE:-0}" = 1 ] || exit 1
    warn "FORCE=1 set — launching despite the backend being down."
fi

step "Starting dev server + sideloading into Word"
echo "    (webpack serves https://localhost:3000 and proxies /auth + /api to the"
echo "     local backends; Word opens with the add-in.)"
echo "    In Word: Home → Mike Legal AI → Open Mike"
# Tell webpack where to proxy backend calls (tracks the real backend ports).
export SUPABASE_PROXY_TARGET="${SUPA_URL:-http://127.0.0.1:54321}"
export API_PROXY_TARGET="$API_BASE"
set -a
# shellcheck disable=SC1091
source .env.development
set +a
exec npm start
