#!/usr/bin/env bash
# Generate the secrets for an air-gapped deployment (plan phase 5).
#
# Emits a .env with a CSPRNG JWT secret, the anon + service_role JWTs DERIVED
# from it (so GoTrue/PostgREST/supabase-js all agree), plus DB/Redis/MinIO
# passwords and the app's encryption/signing secrets. Replaces the Supabase DEMO
# values in docker-compose.airgapped.yml.
#
# Usage: airgapped/scripts/gen-secrets.sh > airgapped/.env.generated
# Requires: openssl. Deterministic-free (uses the CSPRNG); run once, then keep the
# output in a secrets manager. Restores MUST reuse this same file (encrypted data
# is only decryptable with the original secrets — see the backup runbook).
set -euo pipefail

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# HS256 JWT signed with $1 (secret) carrying role $2, long-lived (10y).
mint_jwt() {
    local secret="$1" role="$2"
    local now exp header payload signing sig
    now="$(date +%s)"; exp="$((now + 315360000))"
    header="$(printf '%s' '{"alg":"HS256","typ":"JWT"}' | b64url)"
    payload="$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$now" "$exp" | b64url)"
    signing="${header}.${payload}"
    sig="$(printf '%s' "$signing" | openssl dgst -sha256 -hmac "$secret" -binary | b64url)"
    printf '%s.%s' "$signing" "$sig"
}

rand() { openssl rand -hex "${1:-32}"; }

JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
ANON_KEY="$(mint_jwt "$JWT_SECRET" anon)"
SERVICE_ROLE_KEY="$(mint_jwt "$JWT_SECRET" service_role)"
POSTGRES_PASSWORD="$(rand 24)"
REDIS_PASSWORD="$(rand 24)"
MINIO_ROOT_PASSWORD="$(rand 24)"

cat <<EOF
# GENERATED by gen-secrets.sh — DO NOT COMMIT. Keep in a secrets manager.
# Restores must reuse this file (encrypted data needs the ORIGINAL secrets).

# --- Supabase / JWT (JWT_SECRET signs both keys; all three must stay in sync) ---
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_SECRET_KEY=${SERVICE_ROLE_KEY}

# --- Datastore passwords (db-init aligns the Postgres service roles to these) ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
MINIO_ROOT_USER=mike
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# --- App encryption/signing secrets (>=32 chars; rotating these breaks existing
#     encrypted data unless re-encrypted — see backup runbook) ---
USER_API_KEYS_ENCRYPTION_SECRET=$(rand 32)
MCP_CONNECTORS_ENCRYPTION_SECRET=$(rand 32)
DOWNLOAD_SIGNING_SECRET=$(rand 32)

# --- Email (optional). Login/signup work with NO mail. Only email-CHANGE sends
#     mail; leave these at the Mailpit catcher unless you have an internal relay,
#     in which case set SMTP_* and SECURE_EMAIL_CHANGE=true. ---
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_USER=
SMTP_PASS=
SMTP_ADMIN_EMAIL=admin@mike.local
SECURE_EMAIL_CHANGE=false

# --- Service wiring (internal compose network) ---
SUPABASE_URL=http://gateway:8000
SUPABASE_ANON_KEY=${ANON_KEY}
NEXT_PUBLIC_SUPABASE_URL=http://gateway:8000
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${ANON_KEY}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
# Object storage → MinIO (S3-compatible)
R2_ENDPOINT_URL=http://minio:9000
R2_ACCESS_KEY_ID=mike
R2_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
R2_BUCKET_NAME=mike
R2_REGION=local

# --- Air-gap mode ---
AIRGAPPED=true
NODE_ENV=production
OPENAI_BASE_URL=http://ollama:11434/v1
OPENAI_ALLOW_LOCAL_BASE_URL=true
OPENAI_API_KEY=ollama
ENABLE_OLLAMA=true
# Local model used when a request would otherwise fall back to a cloud default
# (main chat / title / tabular). Must be a registered Ollama model.
AIRGAP_DEFAULT_MODEL=llama3.3
EOF
